# Generated by Django 5.2.6 on 2025-09-16 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_background_color',
            field=models.CharField(blank=True, default='#5a6c7d', max_length=7, verbose_name='Hintergrundfarbe (Unterlagen-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_content_background',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=30, verbose_name='Hintergrundfarbe Beschreibung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_details_text',
            field=models.TextField(blank=True, default='<ul><li><strong>Freigaben:</strong> Verwalten Sie alle wichtigen Dokumente und Berechtigungen.</li><li><strong>Dokumente:</strong> Organisieren Sie Ihre wichtigen Unterlagen sicher.</li><li><strong>Trauerdruck:</strong> Gestalten Sie persönliche Erinnerungsstücke.</li></ul>', verbose_name='Detaillierte Beschreibung (Unterlagen)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_details_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Beschreibungstext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_details_text_size',
            field=models.CharField(blank=True, default='0.95rem', max_length=10, verbose_name='Schriftgröße Beschreibungstext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild (Unterlagen-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_sidetext',
            field=models.CharField(blank=True, default='Unterlagen', max_length=50, verbose_name='Seitentext (Unterlagen-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_sidetext_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=30, verbose_name='Farbe Seitentext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_sidetext_size',
            field=models.CharField(blank=True, default='3.2rem', max_length=10, verbose_name='Schriftgröße Seitentext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_title',
            field=models.CharField(blank=True, default='Unterlagen', max_length=100, verbose_name='Titel (Unterlagen-Beschreibung)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_title_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unterlagen_card_title_size',
            field=models.CharField(blank=True, default='2.5rem', max_length=10, verbose_name='Schriftgröße Titel'),
        ),
    ]
