# Generated by Django 5.2.5 on 2025-08-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_mediaasset_file_mediaasset_file_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorialevent',
            name='location',
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='condolence_note',
            field=models.CharField(blank=True, default='Von Beileidsbezeugungen am Grab bitten wir Abstand zu nehmen.', help_text="z.B. 'Von Beileidsbezeugungen am Grab bitten wir Abstand zu nehmen.'", max_length=255, verbose_name='Hinweis zu Kondolenzbezeugungen'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='donation_for',
            field=models.CharField(blank=True, help_text="z.B. 'Krebshilfe Österreich', 'Tierheim St. Pölten'", max_length=255, verbose_name='Spende zugunsten von'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='dresscode',
            field=models.CharField(blank=True, help_text="z.B. 'Dunkle Kleidung erbeten', 'In Gedenken an seine Lebensfreude bitten wir um helle Kleidung'", max_length=255, verbose_name='Dresscode'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, ist der gesamte Termin nicht sichtbar.', verbose_name='Termin öffentlich anzeigen'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse (Straße, PLZ, Ort)'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='location_name',
            field=models.CharField(blank=True, help_text="z.B. 'Pfarrkirche St. Stephan', 'Zentralfriedhof, Tor 2'", max_length=255, verbose_name='Ort (Name)'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='show_condolence_note',
            field=models.BooleanField(default=True, verbose_name='Kondolenz-Hinweis anzeigen'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='show_donation_info',
            field=models.BooleanField(default=False, verbose_name='Spendeninformationen anzeigen'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='show_dresscode',
            field=models.BooleanField(default=False, verbose_name='Dresscode anzeigen'),
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='show_location',
            field=models.BooleanField(default=True, verbose_name='Ort anzeigen'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='description',
            field=models.TextField(blank=True, help_text='Platz für zusätzliche Informationen, z.B. zum anschließenden Leichenschmaus.', verbose_name='Weitere Details'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.memorialpage', verbose_name='Zugehörige Gedenkseite'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='title',
            field=models.CharField(help_text="z.B. 'Trauerfeier', 'Beisetzung', 'Rosenkranz'", max_length=255, verbose_name='Titel des Termins'),
        ),
    ]
