# Generated by Django 5.2.6 on 2025-09-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesettings_unterlagen_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='unterlagen_card_details_text',
            field=models.TextField(blank=True, default='<ul><li><strong>Dokumente verwalten:</strong> Laden Sie wichtige Unterlagen sicher hoch.</li><li><strong>Schneller Zugriff:</strong> Finden Sie Verträge und Nachweise sofort.</li><li><strong>Sicherheit:</strong> Ihre Daten bleiben geschützt und privat.</li></ul>', verbose_name='Detaillierte Beschreibung (Unterlagen)'),
        ),
    ]
