# Generated by Django 5.2.5 on 2025-08-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_eventattendance_table'),
    ]

    operations = [
    ]
