# Generated by Django 5.2.5 on 2025-08-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_contractitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[("'Roboto', sans-serif", 'Roboto'), ("'Open Sans', sans-serif", 'Open Sans'), ("'Lato', sans-serif", 'Lato'), ("'Montserrat', sans-serif", 'Montserrat'), ("'Source Sans Pro', sans-serif", 'Source Sans Pro')], default="'Roboto', sans-serif", max_length=100, verbose_name='Schriftart'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='font_size_base',
            field=models.CharField(blank=True, default='14px', help_text='CSS-Wert, z.B. 14px oder 0.9rem', max_length=10, verbose_name='Grundschriftgröße'),
        ),
    ]
