# Generated by Django 5.2.5 on 2025-08-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_memorialevent_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Pfarrkirche St. Stephan'", max_length=255, verbose_name='Name des Ortes')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse (Straße, PLZ, Ort)')),
            ],
            options={
                'verbose_name': 'Veranstaltungsort',
                'verbose_name_plural': 'Veranstaltungsorte (Stammdaten)',
            },
        ),
        migrations.RemoveField(
            model_name='memorialevent',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='memorialevent',
            name='location_name',
        ),
        migrations.AddField(
            model_name='memorialevent',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.eventlocation', verbose_name='Veranstaltungsort'),
        ),
    ]
