# Generated by Django 5.2.6 on 2025-09-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sitesettings_font_family_sitesettings_font_size_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vorsorgender', 'Vorsorgender'), ('angehoeriger', 'Angehöriger'), ('verstorbener', 'Verstorbener'), ('gast', 'Gast'), ('administrator', 'Administrator')], default='vorsorgender', max_length=20, verbose_name='Rolle'),
        ),
    ]
