# Generated by Django 5.2.6 on 2025-09-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sitesettings_unterlagen_card_background_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trauerdruckfreigabe',
            unique_together=set(),
        ),
    ]
