# Generated by Django 5.2.5 on 2025-08-17 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_memorialpage_farewell_text_inverted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorialpage',
            name='obituary_card_publication_date',
        ),
        migrations.RemoveField(
            model_name='memorialpage',
            name='show_obituary_card',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quick_link_abschied_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quick_link_kondolieren_icon',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='quick_link_leben_icon',
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255, verbose_name='Name des Gastes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zusage am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.memorialevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teilnahme',
                'verbose_name_plural': 'Teilnahmen',
                'ordering': ['-created_at'],
            },
        ),
    ]
