# Generated by Django 5.2.6 on 2025-09-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylink',
            name='relationship',
            field=models.CharField(blank=True, help_text='z.B. Sohn, Ehefrau, Guter Freund', max_length=100, verbose_name='Verwandtschaftsbezeichnung'),
        ),
    ]
