# Generated by Django 5.2.6 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_familylink_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylink',
            name='can_edit_memorial_page',
            field=models.BooleanField(default=False, verbose_name='Gedenkseite bearbeiten'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='can_edit_precaution_data',
            field=models.BooleanField(default=False, verbose_name='Vorsorge bearbeiten'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='can_view_precaution_data',
            field=models.BooleanField(default=False, verbose_name='Vorsorge einsehen'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False, help_text='Admin bestätigt die Berechtigung (auch ohne Vollmacht-Upload).', verbose_name='Vom Admin validiert'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='power_of_attorney',
            field=models.FileField(blank=True, null=True, upload_to='power_of_attorney/%Y/%m/', verbose_name='Vollmacht (PDF, JPG, PNG)'),
        ),
    ]
