# Generated by Django 5.2.6 on 2025-09-16 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_trauerdruckfreigabe_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trauerdruckentwurf',
            name='design_file',
        ),
        migrations.RemoveField(
            model_name='trauerdruckentwurf',
            name='preview_file',
        ),
        migrations.CreateModel(
            name='TrauerdruckDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="z.B. 'Variante A', 'Klassisch', 'Modern'", max_length=200, verbose_name='Design-Titel')),
                ('description', models.TextField(blank=True, help_text='Beschreibung dieser Design-Variante', verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Ist diese Design-Variante zur Abstimmung verfügbar?', verbose_name='Aktiv')),
                ('is_approved', models.BooleanField(default=False, help_text='Wurde diese Variante von der Familie freigegeben?', verbose_name='Freigegeben')),
                ('order', models.PositiveIntegerField(default=0, help_text='Reihenfolge der Anzeige', verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('design_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trauerdruck_design_files', to='api.mediaasset', verbose_name='Design-Datei')),
                ('entwurf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='api.trauerdruckentwurf', verbose_name='Entwurf')),
                ('preview_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trauerdruck_preview_files', to='api.mediaasset', verbose_name='Vorschau-Datei')),
            ],
            options={
                'verbose_name': 'Trauerdruck-Design',
                'verbose_name_plural': 'Trauerdruck-Designs',
                'ordering': ['entwurf', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrauerdruckDesignFreigabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Entscheidung')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Entschieden am')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freigaben', to='api.trauerdruckdesign', verbose_name='Design')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Prüfer')),
            ],
            options={
                'verbose_name': 'Trauerdruck-Design-Freigabe',
                'verbose_name_plural': 'Trauerdruck-Design-Freigaben',
                'ordering': ['-created_at'],
            },
        ),
    ]
