# Generated by Django 5.2.6 on 2025-09-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_trauerdruckentwurf_design_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-Mail-Adresse'),
        ),
    ]
