# Generated by Django 5.0.4 on 2024-05-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240514_2155'), # Bitte den Namen der vorherigen Migration anpassen
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ordnername')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.mediafolder', verbose_name='Übergeordneter Ordner')),
            ],
            options={
                'verbose_name': 'Medien-Ordner',
                'verbose_name_plural': 'Medien-Ordner',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.mediafolder', verbose_name='Ordner'),
        ),
    ]

