# Generated by Django 5.2.6 on 2025-09-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylink',
            name='can_manage_proofs',
            field=models.BooleanField(default=False, verbose_name='Beweise verwalten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-Mail-Adresse'),
        ),
    ]
