# Generated by Django 5.0.4 on 2025-09-06 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mediafolder_and_asset_folder_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafolder',
            name='memorial_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folder', to='api.memorialpage', verbose_name='Zugehörige Gedenkseite'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.mediafolder', verbose_name='Ordner'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Wird automatisch aus dem Namen generiert, wenn leer gelassen.', max_length=255, unique=True, verbose_name='URL-Alias'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vorsorgender', 'Vorsorgender'), ('angehoeriger', 'Angehöriger'), ('verstorbener', 'Verstorbener'), ('gast', 'Gast'), ('administrator', 'Administrator')], default='vorsorgender', max_length=20, verbose_name='Rolle'),
        ),
    ]
