# Generated by Django 5.2.6 on 2025-09-18 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_can_manage_proofs_to_familylink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familylink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Angehörigen-Verknüpfung', 'verbose_name_plural': 'Angehörigen-Verknüpfungen'},
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='can_edit_memorial_page',
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='can_edit_precaution_data',
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='can_manage_proofs',
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='can_view_precaution_data',
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='is_main_contact',
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='familylink',
            name='power_of_attorney',
        ),
        migrations.AddField(
            model_name='familylink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='created_by',
            field=models.ForeignKey(help_text='Admin der die Verknüpfung erstellt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_links', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Aktive Verknüpfung', verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='notes',
            field=models.TextField(blank=True, help_text='Interne Notizen für Admins', verbose_name='Interne Notizen'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='permission_level',
            field=models.CharField(choices=[('view_only', 'Nur anzeigen'), ('edit_memorial', 'Gedenkseite bearbeiten'), ('manage_all', 'Vollzugriff (Vorsorge + Gedenkseite)')], default='view_only', help_text='Was darf der Angehörige tun?', max_length=20, verbose_name='Berechtigungsstufe'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='role',
            field=models.CharField(choices=[('family_member', 'Familienmitglied'), ('main_contact', 'Hauptansprechpartner'), ('executor', 'Testamentsvollstrecker'), ('guardian', 'Vormund/Betreuer')], default='family_member', help_text='Rolle des Angehörigen', max_length=20, verbose_name='Rolle'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validiert am'),
        ),
        migrations.AddField(
            model_name='familylink',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_family_links', to=settings.AUTH_USER_MODEL, verbose_name='Validiert von'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='deceased_user',
            field=models.ForeignKey(limit_choices_to={'role': 'verstorbener'}, on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_deceased', to=settings.AUTH_USER_MODEL, verbose_name='Verstorbener'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False, help_text='Admin hat die Verknüpfung bestätigt', verbose_name='Vom Admin validiert'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='relative_user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['vorsorgender', 'angehoeriger']}, on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_relative', to=settings.AUTH_USER_MODEL, verbose_name='Angehöriger'),
        ),
    ]
