# Generated by Django 5.2.6 on 2025-09-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_background_color',
            field=models.CharField(blank=True, default='#f4f1ee', help_text='Hex-Code', max_length=7, verbose_name='Hintergrundfarbe Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_button_color',
            field=models.CharField(blank=True, default='#8c8073', help_text='Hex-Code', max_length=7, verbose_name='Button-Farbe Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_button_text_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Hex-Code', max_length=7, verbose_name='Button-Textfarbe Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_card_background_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Hex-Code', max_length=7, verbose_name='Karten-Hintergrundfarbe Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_subtitle',
            field=models.TextField(blank=True, default='Melden Sie sich an, um auf Ihr persönliches Vorsorge-Dashboard zuzugreifen und Gedenkseiten zu verwalten.', verbose_name='Untertitel Login-Seite'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', help_text='Hex-Code', max_length=7, verbose_name='Textfarbe Login'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='login_title',
            field=models.CharField(blank=True, default='Willkommen zurück', max_length=100, verbose_name='Titel Login-Seite'),
        ),
    ]

