# Generated by Django 5.2.6 on 2025-09-22 19:03

from django.db import migrations


def migrate_familylink_data(apps, schema_editor):
    """
    Migriert bestehende FamilyLink-Daten auf die neue Struktur
    """
    FamilyLink = apps.get_model('api', 'FamilyLink')
    
    # Alle bestehenden FamilyLinks abrufen
    family_links = FamilyLink.objects.all()
    
    for link in family_links:
        # Setze Standardwerte für neue Felder basierend auf alten Feldern
        if hasattr(link, 'is_main_contact') and link.is_main_contact:
            link.role = 'main_contact'
        else:
            link.role = 'family_member'
        
        # Setze permission_level basierend auf alten Berechtigungen
        if hasattr(link, 'can_edit_precaution_data') and link.can_edit_precaution_data:
            link.permission_level = 'manage_all'
        elif hasattr(link, 'can_edit_memorial_page') and link.can_edit_memorial_page:
            link.permission_level = 'edit_memorial'
        else:
            link.permission_level = 'view_only'
        
        # Setze Standardwerte für neue Felder
        link.is_active = True
        link.is_validated_by_admin = False
        
        # Speichere die Änderungen
        link.save()


def reverse_migrate_familylink_data(apps, schema_editor):
    """
    Reverse-Migration (nicht implementiert, da alte Felder entfernt wurden)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_redesign_familylink_system'),
    ]

    operations = [
        migrations.RunPython(migrate_familylink_data, reverse_migrate_familylink_data),
    ]
