# Generated by Django 5.2.6 on 2025-09-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_Login'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='register_background_color',
            field=models.CharField(blank=True, help_text='Hex-Code', max_length=7, verbose_name='Hintergrundfarbe Registrierung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild Registrierung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_button_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Button-Farbe Registrierung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_button_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Button-Textfarbe Registrierung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_card_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Hintergrundfarbe Registrierungs-Karte'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_subtitle',
            field=models.TextField(blank=True, default='Erstellen Sie Ihr Konto, um mit der Vorsorge zu beginnen oder einem geliebten Menschen zu gedenken.', verbose_name='Untertitel Registrierungsseite'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Textfarbe Registrierungs-Karte'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_title',
            field=models.CharField(blank=True, default='Konto erstellen', max_length=100, verbose_name='Titel Registrierungsseite'),
        ),
    ]
