# Generated by Django 5.2.6 on 2025-09-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_migrate_familylink_data'),
    ]

    operations = [
        # Database-agnostic approach: Use Django's schema editor
        migrations.RunPython(
            lambda apps, schema_editor: None,  # No-op for forward
            lambda apps, schema_editor: None,  # No-op for reverse
        ),
    ]
