# Generated by Django 5.2.6 on 2025-09-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_Register'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='register_info_panel_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Bild im Info-Panel (Registrierung)'),
        ),
    ]
