# Generated by Django 5.2.6 on 2025-09-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix_familylink_primary_key'),
    ]

    operations = [
        # Emergency fix: Recreate the entire FamilyLink table with correct structure
        migrations.RunSQL(
            """
            -- Drop existing table if it exists and recreate with correct structure
            DROP TABLE IF EXISTS api_familylink CASCADE;
            
            CREATE TABLE api_familylink (
                id SERIAL PRIMARY KEY,
                relationship VARCHAR(100) DEFAULT '',
                role VARCHAR(20) DEFAULT 'family_member',
                permission_level VARCHAR(20) DEFAULT 'view_only',
                is_active BOOLEAN DEFAULT TRUE,
                is_validated_by_admin BOOLEAN DEFAULT FALSE,
                validated_at TIMESTAMP WITH TIME ZONE NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                deceased_user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                relative_user_id INTEGER NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE,
                validated_by_id INTEGER NULL REFERENCES auth_user(id) ON DELETE SET NULL,
                created_by_id INTEGER NULL REFERENCES auth_user(id) ON DELETE SET NULL,
                notes TEXT DEFAULT ''
            );
            
            -- Add constraints
            ALTER TABLE api_familylink ADD CONSTRAINT api_familylink_deceased_user_id_fkey 
                FOREIGN KEY (deceased_user_id) REFERENCES auth_user(id) ON DELETE CASCADE;
            ALTER TABLE api_familylink ADD CONSTRAINT api_familylink_relative_user_id_fkey 
                FOREIGN KEY (relative_user_id) REFERENCES auth_user(id) ON DELETE CASCADE;
            ALTER TABLE api_familylink ADD CONSTRAINT api_familylink_validated_by_id_fkey 
                FOREIGN KEY (validated_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
            ALTER TABLE api_familylink ADD CONSTRAINT api_familylink_created_by_id_fkey 
                FOREIGN KEY (created_by_id) REFERENCES auth_user(id) ON DELETE SET NULL;
            
            -- Add unique constraint
            ALTER TABLE api_familylink ADD CONSTRAINT api_familylink_unique 
                UNIQUE (deceased_user_id, relative_user_id);
            
            -- Add indexes
            CREATE INDEX api_familylink_deceased_user_id_idx ON api_familylink(deceased_user_id);
            CREATE INDEX api_familylink_relative_user_id_idx ON api_familylink(relative_user_id);
            CREATE INDEX api_familylink_created_at_idx ON api_familylink(created_at);
            """,
            reverse_sql="DROP TABLE IF EXISTS api_familylink CASCADE;"
        ),
    ]
