# Generated by Django 5.2.6 on 2025-09-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_Register2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='register_info_panel_image_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (füllend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Info-Panel Bild'),
        ),
    ]
