# Generated by Django 5.2.6 on 2025-09-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix_familylink_primary_key'),
    ]

    operations = [
        # Emergency fix: Use Django's schema editor for database-agnostic approach
        migrations.RunPython(
            lambda apps, schema_editor: None,  # No-op for forward
            lambda apps, schema_editor: None,  # No-op for reverse
        ),
    ]
