# Generated by Django 5.2.6 on 2025-09-07 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_Register3'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_background_color',
            field=models.CharField(blank=True, help_text='Hex-Code', max_length=7, verbose_name='Hintergrundfarbe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_button_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Button-Farbe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_button_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Button-Textfarbe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_card_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Karten-Hintergrundfarbe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_confirm_subtitle',
            field=models.TextField(blank=True, default='Bitte geben Sie Ihr neues Passwort ein und bestätigen Sie es.', verbose_name='Untertitel (Neues Passwort)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_confirm_title',
            field=models.CharField(blank=True, default='Neues Passwort festlegen', max_length=100, verbose_name='Titel (Neues Passwort)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_subtitle',
            field=models.TextField(blank=True, default='Geben Sie Ihre E-Mail-Adresse ein. Wir senden Ihnen einen Link, um Ihr Passwort zurückzusetzen.', verbose_name='Untertitel (Passwort anfordern)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Textfarbe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='password_reset_title',
            field=models.CharField(blank=True, default='Passwort vergessen?', max_length=100, verbose_name='Titel (Passwort anfordern)'),
        ),
    ]
