# Generated by Django 5.2.6 on 2025-09-22 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_emergency_fix_familylink_table'),
    ]

    operations = [
    ]
