# Generated by Django 5.2.6 on 2025-09-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_Register4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='login_background_color',
            field=models.CharField(blank=True, help_text='Hex-Code', max_length=7, verbose_name='Hintergrundfarbe Login'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_button_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Button-Farbe Login'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_button_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Button-Textfarbe Login'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_card_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Hintergrundfarbe Login-Karte'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Textfarbe Login-Karte'),
        ),
    ]
