# Generated by Django 5.2.6 on 2025-09-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_sitesettings_login_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_background_color',
            field=models.CharField(blank=True, default='#f4f1ee', max_length=7, verbose_name='Hintergrundfarbe (Mein Bereich)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild (Mein Bereich)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_container_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Hintergrundfarbe Container'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_dashboard_subtitle',
            field=models.TextField(blank=True, default='Hier haben Sie den zentralen Überblick über Ihre Vorsorge und Ihre Gedenkseiten.', verbose_name='Untertitel (Dashboard)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_dashboard_title',
            field=models.CharField(blank=True, default='Willkommen in Ihrem persönlichen Bereich', max_length=100, verbose_name='Titel (Dashboard)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_active_background_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Hintergrundfarbe (Aktiv)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_active_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Textfarbe (Aktiv)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_background_color',
            field=models.CharField(blank=True, default='#f9f9f9', max_length=7, verbose_name='Hintergrundfarbe Sidebar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_text_color',
            field=models.CharField(blank=True, default='#6d6d6d', max_length=7, verbose_name='Textfarbe Sidebar'),
        ),
    ]

