# Generated by Django 5.2.6 on 2025-09-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_0014_sitesettings_password_reset_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="search_filter_active_color",
            field=models.CharField(
                blank=True,
                default="#8c8073",
                max_length=7,
                verbose_name="Filter-Menü Aktiv Hintergrund",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_filter_active_text_color",
            field=models.CharField(
                blank=True,
                default="#FFFFFF",
                max_length=7,
                verbose_name="Filter-Menü Aktiv Text",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_filter_button_color",
            field=models.CharField(
                blank=True,
                default="#e5e0da",
                max_length=7,
                verbose_name="Filter-Button Hintergrund",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_filter_button_icon_color",
            field=models.CharField(
                blank=True,
                default="#3a3a3a",
                max_length=7,
                verbose_name="Filter-Button Icon",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_filter_menu_color",
            field=models.CharField(
                blank=True,
                default="#FFFFFF",
                max_length=7,
                verbose_name="Filter-Menü Hintergrund",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="search_filter_menu_text_color",
            field=models.CharField(
                blank=True,
                default="#3a3a3a",
                max_length=7,
                verbose_name="Filter-Menü Text",
            ),
        ),
    ]

