# Generated by Django 5.2.6 on 2025-09-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_Test'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='listing_card_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', help_text='Hex-Code, z.B. #3a3a3a', max_length=7, verbose_name='Karten-Textfarbe'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='listing_text_color',
            field=models.CharField(blank=True, help_text='Hex-Code, z.B. #3a3a3a', max_length=7, verbose_name='Titel-Textfarbe'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='listing_title',
            field=models.CharField(blank=True, default='Wir gedenken', max_length=100, verbose_name='Titel über den Gedenkkarten'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_background_color',
            field=models.CharField(blank=True, default='#f4f1ee', max_length=7, verbose_name='Hintergrundfarbe (Seite)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild (Seite)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_container_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Hintergrundfarbe (Container)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_dashboard_subtitle',
            field=models.TextField(blank=True, default='Hier haben Sie den Überblick und Zugriff auf alle Ihre persönlichen Daten, Vorsorge-Dokumente und Gedenkseiten.', verbose_name='Dashboard Untertitel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_dashboard_title',
            field=models.CharField(blank=True, default='Willkommen in Ihrem Bereich', max_length=100, verbose_name='Dashboard Titel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_active_background_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Sidebar Aktiv Hintergrund'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_active_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Sidebar Aktiv Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_background_color',
            field=models.CharField(blank=True, default='#f8f9fa', max_length=7, verbose_name='Sidebar Hintergrund'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_sidebar_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Sidebar Text'),
        ),
    ]
