# Generated by Django 5.2.6 on 2025-09-10 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sitesettings_listing_card_text_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractitem',
            options={'verbose_name': 'Vertrags-Eintrag', 'verbose_name_plural': 'Vertrags-EintrÃ¤ge'},
        ),
        migrations.AlterModelOptions(
            name='digitallegacyitem',
            options={'verbose_name': 'Digitaler Nachlass Eintrag', 'verbose_name_plural': 'Digitale Nachlass EintrÃ¤ge'},
        ),
        migrations.AlterModelOptions(
            name='familylink',
            options={'verbose_name': 'AngehÃ¶rigen-VerknÃ¼pfung', 'verbose_name_plural': 'AngehÃ¶rigen-VerknÃ¼pfungen'},
        ),
        migrations.AlterModelOptions(
            name='financialitem',
            options={'verbose_name': 'Finanz-Eintrag', 'verbose_name_plural': 'Finanz-EintrÃ¤ge'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Galerie-Eintrag', 'verbose_name_plural': 'Galerie-EintrÃ¤ge'},
        ),
        migrations.AlterModelOptions(
            name='insuranceitem',
            options={'verbose_name': 'Versicherungs-Eintrag', 'verbose_name_plural': 'Versicherungs-EintrÃ¤ge'},
        ),
        migrations.AlterModelOptions(
            name='lastwishes',
            options={'verbose_name': 'Letzter Wunsch', 'verbose_name_plural': 'Letzte WÃ¼nsche'},
        ),
        migrations.AlterField(
            model_name='candlemessagetemplate',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titel (fÃ¼r Dropdown)'),
        ),
        migrations.AlterField(
            model_name='condolencetemplate',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titel (fÃ¼r Dropdown)'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='notice_period',
            field=models.CharField(blank=True, max_length=255, verbose_name='KÃ¼ndigungsfrist'),
        ),
        migrations.AlterField(
            model_name='digitallegacyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geÃ¤ndert'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse (StraÃŸe, PLZ, Ort)'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False, help_text='Admin bestÃ¤tigt die Berechtigung (auch ohne Vollmacht-Upload).', verbose_name='Vom Admin validiert'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='relative_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_relative', to=settings.AUTH_USER_MODEL, verbose_name='AngehÃ¶riger'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='flower_wishes',
            field=models.TextField(blank=True, verbose_name='BlumenwÃ¼nsche'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='music_wishes',
            field=models.JSONField(blank=True, default=list, verbose_name='MusikwÃ¼nsche'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='speaker_wishes',
            field=models.TextField(blank=True, verbose_name='RednerwÃ¼nsche'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geÃ¤ndert'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='memorial_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folder', to='api.memorialpage', verbose_name='ZugehÃ¶rige Gedenkseite'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.mediafolder', verbose_name='Ãœbergeordneter Ordner'),
        ),
        migrations.AlterField(
            model_name='memorialcandle',
            name='candle_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.candleimage', verbose_name='AusgewÃ¤hltes Kerzenbild'),
        ),
        migrations.AlterField(
            model_name='memorialcandle',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Nur fÃ¼r Familie'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='description',
            field=models.TextField(blank=True, help_text='Platz fÃ¼r zusÃ¤tzliche Informationen, z.B. zum anschlieÃŸenden Leichenschmaus.', verbose_name='Weitere Details'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='donation_for',
            field=models.CharField(blank=True, help_text="z.B. 'Krebshilfe Ã–sterreich', 'Tierheim St. PÃ¶lten'", max_length=255, verbose_name='Spende zugunsten von'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, ist der gesamte Termin nicht sichtbar.', verbose_name='Termin Ã¶ffentlich anzeigen'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.memorialpage', verbose_name='ZugehÃ¶rige Gedenkseite'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='farewell_background_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (fÃ¼llend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Hintergrundbild Abschied'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='farewell_text_inverted',
            field=models.BooleanField(default=False, verbose_name='Textfarbe im Abschiedsbereich umkehren (fÃ¼r helle HintergrÃ¼nde)'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='hero_background_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (fÃ¼llend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Hintergrundbild Hero'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='memorial_picture_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Gedenkbild RÃ¼ckseite'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geÃ¤ndert'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_size_base',
            field=models.CharField(blank=True, default='14px', help_text='CSS-Wert, z.B. 14px oder 0.9rem', max_length=10, verbose_name='GrundschriftgrÃ¶ÃŸe'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='listing_title',
            field=models.CharField(blank=True, default='Wir gedenken', max_length=100, verbose_name='Titel Ã¼ber den Gedenkkarten'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_subtitle',
            field=models.TextField(blank=True, default='Melden Sie sich an, um auf Ihr persÃ¶nliches Vorsorge-Dashboard zuzugreifen und Gedenkseiten zu verwalten.', verbose_name='Untertitel Login-Seite'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_title',
            field=models.CharField(blank=True, default='Willkommen zurÃ¼ck', max_length=100, verbose_name='Titel Login-Seite'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_dashboard_subtitle',
            field=models.TextField(blank=True, default='Hier haben Sie den Ãœberblick und Zugriff auf alle Ihre persÃ¶nlichen Daten, Vorsorge-Dokumente und Gedenkseiten.', verbose_name='Dashboard Untertitel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password_reset_confirm_subtitle',
            field=models.TextField(blank=True, default='Bitte geben Sie Ihr neues Passwort ein und bestÃ¤tigen Sie es.', verbose_name='Untertitel (Neues Passwort)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password_reset_subtitle',
            field=models.TextField(blank=True, default='Geben Sie Ihre E-Mail-Adresse ein. Wir senden Ihnen einen Link, um Ihr Passwort zurÃ¼ckzusetzen.', verbose_name='Untertitel (Passwort anfordern)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='register_info_panel_image_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (fÃ¼llend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Info-Panel Bild'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_active_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Filter-MenÃ¼ Aktiv Hintergrund'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_active_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Filter-MenÃ¼ Aktiv Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_menu_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Filter-MenÃ¼ Hintergrund'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_menu_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Filter-MenÃ¼ Text'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completeness',
            field=models.IntegerField(default=0, verbose_name='Profil-VollstÃ¤ndigkeit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vorsorgender', 'Vorsorgender'), ('angehoeriger', 'AngehÃ¶riger'), ('verstorbener', 'Verstorbener'), ('gast', 'Gast'), ('administrator', 'Administrator')], default='vorsorgender', max_length=20, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geÃ¤ndert'),
        ),
    ]
