# Generated by Django 5.2.6 on 2025-09-11 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_contractitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractitem',
            options={'verbose_name': 'Vertrags-Eintrag', 'verbose_name_plural': 'Vertrags-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='digitallegacyitem',
            options={'verbose_name': 'Digitaler Nachlass Eintrag', 'verbose_name_plural': 'Digitale Nachlass Einträge'},
        ),
        migrations.AlterModelOptions(
            name='familylink',
            options={'verbose_name': 'Angehörigen-Verknüpfung', 'verbose_name_plural': 'Angehörigen-Verknüpfungen'},
        ),
        migrations.AlterModelOptions(
            name='financialitem',
            options={'verbose_name': 'Finanz-Eintrag', 'verbose_name_plural': 'Finanz-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Galerie-Eintrag', 'verbose_name_plural': 'Galerie-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='insuranceitem',
            options={'verbose_name': 'Versicherungs-Eintrag', 'verbose_name_plural': 'Versicherungs-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='lastwishes',
            options={'verbose_name': 'Letzter Wunsch', 'verbose_name_plural': 'Letzte Wünsche'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Bild (Gedenken-Karte)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_subtitle',
            field=models.TextField(blank=True, default='Verwalten Sie Gedenkseiten und teilen Sie Erinnerungen.', verbose_name='Untertitel (Gedenken-Karte)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_title',
            field=models.CharField(blank=True, default='Gedenken', max_length=100, verbose_name='Titel (Gedenken-Karte)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_choice_background_color',
            field=models.CharField(blank=True, default='#f4f1ee', max_length=7, verbose_name='Hintergrundfarbe (Auswahlseite)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_choice_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild (Auswahlseite)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_choice_subtitle',
            field=models.TextField(blank=True, default='Bitte wählen Sie den Bereich aus, den Sie verwalten möchten.', verbose_name='Untertitel (Auswahlseite)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_choice_title',
            field=models.CharField(blank=True, default='Mein Bereich', max_length=100, verbose_name='Titel (Auswahlseite)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Bild (Vorsorge-Karte)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_subtitle',
            field=models.TextField(blank=True, default='Treffen Sie Vorkehrungen und sichern Sie Ihr digitales Erbe.', verbose_name='Untertitel (Vorsorge-Karte)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_title',
            field=models.CharField(blank=True, default='Vorsorge', max_length=100, verbose_name='Titel (Vorsorge-Karte)'),
        ),
        migrations.AlterField(
            model_name='candlemessagetemplate',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titel (für Dropdown)'),
        ),
        migrations.AlterField(
            model_name='condolencetemplate',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titel (für Dropdown)'),
        ),
        migrations.AlterField(
            model_name='contractitem',
            name='notice_period',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kündigungsfrist'),
        ),
        migrations.AlterField(
            model_name='digitallegacyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse (Straße, PLZ, Ort)'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='is_validated_by_admin',
            field=models.BooleanField(default=False, help_text='Admin bestätigt die Berechtigung (auch ohne Vollmacht-Upload).', verbose_name='Vom Admin validiert'),
        ),
        migrations.AlterField(
            model_name='familylink',
            name='relative_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_links_as_relative', to=settings.AUTH_USER_MODEL, verbose_name='Angehöriger'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='flower_wishes',
            field=models.TextField(blank=True, verbose_name='Blumenwünsche'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='music_wishes',
            field=models.JSONField(blank=True, default=list, verbose_name='Musikwünsche'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='speaker_wishes',
            field=models.TextField(blank=True, verbose_name='Rednerwünsche'),
        ),
        migrations.AlterField(
            model_name='lastwishes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='memorial_page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_folder', to='api.memorialpage', verbose_name='Zugehörige Gedenkseite'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.mediafolder', verbose_name='Übergeordneter Ordner'),
        ),
        migrations.AlterField(
            model_name='memorialcandle',
            name='candle_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.candleimage', verbose_name='Ausgewähltes Kerzenbild'),
        ),
        migrations.AlterField(
            model_name='memorialcandle',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Nur für Familie'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='description',
            field=models.TextField(blank=True, help_text='Platz für zusätzliche Informationen, z.B. zum anschließenden Leichenschmaus.', verbose_name='Weitere Details'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='donation_for',
            field=models.CharField(blank=True, help_text="z.B. 'Krebshilfe Österreich', 'Tierheim St. Pölten'", max_length=255, verbose_name='Spende zugunsten von'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, ist der gesamte Termin nicht sichtbar.', verbose_name='Termin öffentlich anzeigen'),
        ),
        migrations.AlterField(
            model_name='memorialevent',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.memorialpage', verbose_name='Zugehörige Gedenkseite'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='farewell_background_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (füllend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Hintergrundbild Abschied'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='farewell_text_inverted',
            field=models.BooleanField(default=False, verbose_name='Textfarbe im Abschiedsbereich umkehren (für helle Hintergründe)'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='hero_background_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (füllend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Hintergrundbild Hero'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='memorial_picture_back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Gedenkbild Rückseite'),
        ),
        migrations.AlterField(
            model_name='memorialpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='font_size_base',
            field=models.CharField(blank=True, default='14px', help_text='CSS-Wert, z.B. 14px oder 0.9rem', max_length=10, verbose_name='Grundschriftgröße'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='listing_title',
            field=models.CharField(blank=True, default='Wir gedenken', max_length=100, verbose_name='Titel über den Gedenkkarten'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_subtitle',
            field=models.TextField(blank=True, default='Melden Sie sich an, um auf Ihr persönliches Vorsorge-Dashboard zuzugreifen und Gedenkseiten zu verwalten.', verbose_name='Untertitel Login-Seite'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='login_title',
            field=models.CharField(blank=True, default='Willkommen zurück', max_length=100, verbose_name='Titel Login-Seite'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mein_bereich_dashboard_subtitle',
            field=models.TextField(blank=True, default='Hier haben Sie den Überblick und Zugriff auf alle Ihre persönlichen Daten, Vorsorge-Dokumente und Gedenkseiten.', verbose_name='Dashboard Untertitel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password_reset_confirm_subtitle',
            field=models.TextField(blank=True, default='Bitte geben Sie Ihr neues Passwort ein und bestätigen Sie es.', verbose_name='Untertitel (Neues Passwort)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password_reset_subtitle',
            field=models.TextField(blank=True, default='Geben Sie Ihre E-Mail-Adresse ein. Wir senden Ihnen einen Link, um Ihr Passwort zurückzusetzen.', verbose_name='Untertitel (Passwort anfordern)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='register_info_panel_image_size',
            field=models.CharField(choices=[('cover', 'Gestreckt (füllend)'), ('contain', 'Eingepasst (komplett sichtbar)')], default='cover', max_length=10, verbose_name='Anpassung Info-Panel Bild'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_active_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Filter-Menü Aktiv Hintergrund'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_active_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Filter-Menü Aktiv Text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_menu_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Filter-Menü Hintergrund'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='search_filter_menu_text_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Filter-Menü Text'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completeness',
            field=models.IntegerField(default=0, verbose_name='Profil-Vollständigkeit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vorsorgender', 'Vorsorgender'), ('angehoeriger', 'Angehöriger'), ('verstorbener', 'Verstorbener'), ('gast', 'Gast'), ('administrator', 'Administrator')], default='vorsorgender', max_length=20, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
    ]
