# Generated by Django 5.2.6 on 2025-09-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_contractitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='gedenken_card_subtitle',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='vorsorge_card_subtitle',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_background_color',
            field=models.CharField(blank=True, default='#8c8073', max_length=7, verbose_name='Hintergrundfarbe (Gedenken-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_content_background',
            field=models.CharField(blank=True, default='rgba(0, 0, 0, 0.5)', max_length=30, verbose_name='Hintergrundfarbe Beschreibung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_details_text',
            field=models.TextField(blank=True, default='<ul><li><strong>Gedenkseiten verwalten:</strong> Erstellen und pflegen Sie eine persönliche Seite.</li><li><strong>Angehörige einladen:</strong> Vergeben Sie Berechtigungen.</li><li><strong>Meine Beiträge:</strong> Sehen Sie all Ihre Kondolenzen und Gedenkkerzen.</li></ul>', verbose_name='Detaillierte Beschreibung (Gedenken)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_details_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Beschreibungstext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_details_text_size',
            field=models.CharField(blank=True, default='0.95rem', max_length=10, verbose_name='Schriftgröße Beschreibungstext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_sidetext',
            field=models.CharField(blank=True, default='Gedenken', max_length=50, verbose_name='Seitentext (Gedenken-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_sidetext_color',
            field=models.CharField(blank=True, default='rgba(255, 255, 255, 0.4)', max_length=30, verbose_name='Farbe Seitentext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_sidetext_size',
            field=models.CharField(blank=True, default='3.2rem', max_length=10, verbose_name='Schriftgröße Seitentext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_title_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gedenken_card_title_size',
            field=models.CharField(blank=True, default='2.5rem', max_length=10, verbose_name='Schriftgröße Titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_background_color',
            field=models.CharField(blank=True, default='#6d6d6d', max_length=7, verbose_name='Hintergrundfarbe (Vorsorge-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_content_background',
            field=models.CharField(blank=True, default='rgba(0, 0, 0, 0.5)', max_length=30, verbose_name='Hintergrundfarbe Beschreibung'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_details_text',
            field=models.TextField(blank=True, default='<ul><li><strong>Meine Vorsorge:</strong> Regeln Sie alles Wichtige von Verträgen bis zum digitalen Nachlass.</li><li><strong>Eigene Gedenkseite:</strong> Gestalten Sie zu Lebzeiten Ihre persönliche Gedenkseite.</li><li><strong>Wichtige Medien:</strong> Verwalten Sie sicher alle Dokumente und Bilder.</li></ul>', verbose_name='Detaillierte Beschreibung (Vorsorge)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_details_text_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Beschreibungstext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_details_text_size',
            field=models.CharField(blank=True, default='0.95rem', max_length=10, verbose_name='Schriftgröße Beschreibungstext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_sidetext',
            field=models.CharField(blank=True, default='Vorsorge', max_length=50, verbose_name='Seitentext (Vorsorge-Säule)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_sidetext_color',
            field=models.CharField(blank=True, default='rgba(255, 255, 255, 0.4)', max_length=30, verbose_name='Farbe Seitentext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_sidetext_size',
            field=models.CharField(blank=True, default='3.2rem', max_length=10, verbose_name='Schriftgröße Seitentext'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_title_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vorsorge_card_title_size',
            field=models.CharField(blank=True, default='2.5rem', max_length=10, verbose_name='Schriftgröße Titel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gedenken_card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild (Gedenken-Säule)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gedenken_card_title',
            field=models.CharField(blank=True, default='Gedenken', max_length=100, verbose_name='Titel (Gedenken-Beschreibung)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vorsorge_card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Hintergrundbild (Vorsorge-Säule)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vorsorge_card_title',
            field=models.CharField(blank=True, default='Vorsorge', max_length=100, verbose_name='Titel (Vorsorge-Beschreibung)'),
        ),
    ]
