# Generated by Django 5.2.6 on 2025-09-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_sitesettings_gedenken_card_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_button_text_size',
            field=models.CharField(blank=True, default='1rem', max_length=10, verbose_name='Schriftgröße Buttons'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_logo_height',
            field=models.CharField(blank=True, default='40px', help_text='CSS-Wert, z.B. 40px', max_length=10, verbose_name='Logo-Höhe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name='Logo-Bild (ersetzt Text)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_site_title_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Farbe Seiten-Titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_site_title_size',
            field=models.CharField(blank=True, default='1.5rem', max_length=10, verbose_name='Schriftgröße Seiten-Titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_site_title_text',
            field=models.CharField(blank=True, default='Gedenken & Vorsorge', max_length=100, verbose_name='Seiten-Titel (Text)'),
        ),
    ]
