# Generated by Django 5.2.6 on 2025-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_sitesettings_header_button_text_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='portal_choice_subtitle_color',
            field=models.CharField(blank=True, default='#6b7280', max_length=7, verbose_name='Farbe Untertitel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_choice_title_color',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Farbe Titel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gedenken_card_content_background',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Hintergrundfarbe Beschreibung'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gedenken_card_sidetext_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Seitentext'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vorsorge_card_content_background',
            field=models.CharField(blank=True, default='#3a3a3a', max_length=7, verbose_name='Hintergrundfarbe Beschreibung'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vorsorge_card_sidetext_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7, verbose_name='Farbe Seitentext'),
        ),
    ]
