# Generated by Django 5.2.5 on 2025-08-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='file',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='media_assets/%Y/%m/', verbose_name='Datei-Upload (Lokal)'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Datei-URL (Extern)'),
        ),
    ]
