# Generated by Django 5.2.5 on 2025-08-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_eventlocation_remove_memorialevent_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialpage',
            name='farewell_text_inverted',
            field=models.BooleanField(default=False, verbose_name='Textfarbe im Abschiedsbereich umkehren (für helle Hintergründe)'),
        ),
        migrations.AddField(
            model_name='memorialpage',
            name='obituary_card_publication_date',
            field=models.DateTimeField(blank=True, help_text='Wenn ein Datum gesetzt ist, wird der Partezettel erst ab diesem Zeitpunkt angezeigt.', null=True, verbose_name='Veröffentlichungsdatum Partezettel'),
        ),
        migrations.AddField(
            model_name='memorialpage',
            name='show_obituary_card',
            field=models.BooleanField(default=True, verbose_name='Partezettel anzeigen'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_abschied_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name="Icon für 'Abschied'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_kondolieren_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name="Icon für 'Kondolieren'"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_link_leben_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.mediaasset', verbose_name="Icon für 'Mein Leben'"),
        ),
    ]
