# docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
    # Weist den Container an, immer wieder neu zu starten, bis er erfolgreich läuft.
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    # KORRIGIERT: PostgreSQL-Version auf 16 aktualisiert, um mit Django kompatibel zu sein.
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vorsorge_user
      - POSTGRES_PASSWORD=vorsorge_pass
      - POSTGRES_DB=vorsorge_db

volumes:
  postgres_data:
