# render.yaml
# KORRIGIERT: Fehlende CORS-Umgebungsvariable hinzugefügt.
# NEU: UTF-8 Kodierung für die Datenbankverbindung erzwungen.

databases:
  - name: vorsorge-db
    plan: free

services:
  # Django Backend Service
  - type: web
    name: vorsorge-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py createsuperuser"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vorsorge-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_SUPERUSER_EMAIL
        value: philipp.pollak855@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "24061998"
      - key: CORS_ALLOWED_ORIGINS 
        value: "https://gedenken.netlify.app http://localhost:3000"
      - key: ALLOWED_HOSTS 
        value: "vorsorge-backend.onrender.com"
      # NEU: Erzwingt die korrekte Client-Kodierung für die Datenbank
      - key: PGCLIENTENCODING
        value: utf8
